### ISSUE TITLE
An option to hide flags icon

### ISSUE THREAD

**Issue by kyudorimj** [tanansatpal/ngx-mat-intl-tel-input#186]
Is there a way to hide the flag icon and let only the country's dial code was there?

Something like this:
![image](https://github.com/tanansatpal/ngx-mat-intl-tel-input/assets/54704849/e917cd95-c4f3-405f-9592-d5a5f7ddb583)

**Comment by rbalet** [comment]
Hi @kyudorimj 

Since this library isn't maintained anymore, I did enhance it in a [library fork](https://github.com/rbalet/ngx-mat-input-tel).

I fixed your issue on the following version: https://github.com/rbalet/ngx-mat-input-tel/releases/tag/v17.1.3

If you wish to test it out ;) https://www.npmjs.com/package/ngx-mat-input-tel

**Comment by cipherleaf** [comment]
Thanks for your work @rbalet 🎉 , I'll check this out when I get back on this. 🙇🏼
